User.create!([
  {email: "guest@gmail.com", password_digest: "$2a$10$ZwKIXyDHwk9fc/wMgSB6S.Vwmw.MkhZtHU1kYCzdg8fUKZaTSlzzS", session_token: "uKvuGXMyFTU-p4JnmoK33g", name: "Guest"},
  {email: "eline@gmail.com", password_digest: "$2a$10$ZwKIXyDHwk9fc/wMgSB6S.Vwmw.MkhZtHU1kYCzdg8fUKZaTSlzzS", session_token: "uKvuGXMyFTU-p4JnmoK33g", name: "Eline"},
  {email: "hudson@gmail.com", password_digest: "$2a$10$Cmidb0/savQeS2zHno.XBO5AzXb2TuDbnzmsMM1VtqwRCOFU78Vzm", session_token: "L_jxz0dvpYo3Ga9y4LQ2Yg", name: "Hudson"},
  {email: "helmut@lang.com", password_digest: "$2a$10$8jC8d3DCWvW0FzAkwAjAHeuAztBYe5G2uk62hHEUu9GsQRGKFtycW", session_token: "SdH7ZPyJfB3K0mTKb-L53g", name: "Helmut"},
  {email: "mrhudson@gmail.com", password_digest: "$2a$10$ZOrquH8DleqzCEXxgOtR1.oA4HAu.S3VL0tP.GCUss9pYe86euchq", session_token: "IUzLXW0x0PaEt3_r4e-vdA", name: "MrHudson"},
  {email: "joep@gmail.com", password_digest: "$2a$10$wO47wDtfL7TDsXcTrB7XYOLUwyg3zaRgp120toxBvrzlK6H2oN0CK", session_token: "sWUckr6eWuf9c3LYqMRiAQ", name: "Joep"},
  {email: "eliesaab@saab.com", password_digest: "$2a$10$DFYTV2t9spgdxPEPWX3tieiMgVgmFFI1trCtp5JGPG3cV3DZbdque", session_token: "lWLEFdixVTvXN6N_CGb0KQ", name: "Elie"},
  {email: "valentino@couture.com", password_digest: "$2a$10$0AGo10QJ6NQc0yMk4ZHRT.qoO7Iyi2x3/iFPo/zE/DX5pxY3wuIgm", session_token: "9uHl0G-mln3e_KmmLZteBA", name: "Valentino"},
  {email: "boy@chanel.com", password_digest: "$2a$10$YdySk4XnDMW6lrYAT3MvLu1pi5ICBKD2UVsEXkap3ecynEU6HP0TO", session_token: "Vjb89PNnX0R-bE6DjlrJ6Q", name: "Chanel"},
  {email: "g@armani.com", password_digest: "$2a$10$BMY.y4wdtmGjXvpcJ2BDbuLwHjeMRi.5oPqYqI2AdVrv3Tk5597i6", session_token: "kH5C0Jg19VmlDd77OqfXeQ", name: "Georgio"},
  {email: "mcqueen@gmail.com", password_digest: "$2a$10$0waPZZqDI3R5W7wTlTnICOa1jcu2Bo/KAdXgQSNUtJ98/AdqLuL5W", session_token: "yX2jSY9kJEQTd235pteuOg", name: "Alexander"},
  {email: "vera@wang.com", password_digest: "$2a$10$suORVQqS5iPksJkGmLTDMeDkHRV4bbbY0ObgMohPcB3FPvxkJw07m", session_token: "MFwtnQzXHhR8kf7qRhzUPg", name: "Vera"},
  {email: "jason@wung.com", password_digest: "$2a$10$CSSwsU6.mJxw7hBrxtZDz.6cSd01zmEuyly1nLkVqcitslJKcopF2", session_token: "qH1kCCvWX9K34RZmN_K5fw", name: "Jason"},
  {email: "yves@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Yves"},
  {email: "person@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Jenny"},
  {email: "person1@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Leighann"},
  {email: "person2@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Michael"},
  {email: "person3@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Antoinet"},
  {email: "person4@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Birdy"},
  {email: "person5@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Jelmer"},
  {email: "person6@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Ate"},
  {email: "person7@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Jo-an"},
  {email: "person8@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Georgina"},
  {email: "person9@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Anastasia"},
  {email: "person10@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "CJ"},
  {email: "person11@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Shawna"},
  {email: "person12@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Jeff"},
  {email: "person13@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Andrew"},
  {email: "person14@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Markov"},
  {email: "person15@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Curie"},
  {email: "person16@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Aaron"},
  {email: "person17@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Auster"},
  {email: "person18@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Danny"},
  {email: "person19@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Lisa"},
  {email: "person20@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Iris"},
  {email: "person21@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Eva"},
  {email: "person22@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Shanne"},
  {email: "person23@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Amanda"},
  {email: "person24@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Emma"},
  {email: "person25@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Chris"},
  {email: "person26@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Rishabh"},
  {email: "person28@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Isis"},
  {email: "person29@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Marie"},
  {email: "person30@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Matt"},
  {email: "person31@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Ryan"},
  {email: "person32@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Yanran"},
  {email: "person33@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Leah"},
  {email: "person34@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Becca"},
  {email: "person35@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Lia"},
  {email: "person36@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Ava"},
  {email: "person37@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Celine"},
  {email: "person38@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Maggie"},
  {email: "person39@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Jennifer"},
  {email: "person40@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Rachel"},
  {email: "person41@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Elodie"},
  {email: "person42@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Mandy"},
  {email: "person43@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Arial"},
  {email: "person44@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Vanessa"},
  {email: "person45@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Ester"},
  {email: "person46@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Ashley"},
  {email: "person47@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Eveline"},
  {email: "person48@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Angela"},
  {email: "person49@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Kim"},
  {email: "person50@gmail.com", password_digest: "$2a$10$MCWKIxXnQPmOum/nb3VqieaaPldz2JMHr/0POuSpYv3G0vh.En0sy", session_token: "PAatYWTIalTY70icBpV9lw", name: "Sacha"},
])
Challenge.create!([
  {name: "Little Black Dress", category: "Dresses", end_date: "2014-12-25", description: "Design the perfect little black dress for any party occassion. Drawing must be full body view. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $150 - $200.", admin_id: 3, background_img: "LBD.jpg"},
  {name: "Party Dress", category: "Dresses", end_date: "2014-12-18", description: "Design a party dress in any color for a fancy night out. Drawing must be full body view. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $200 - $250.", admin_id: 3, background_img: "party_dress.jpg"},
  {name: "High Heels", category: "Shoes", end_date: "2014-12-18", description: "Design a pair of killers heels that will make jaws drop. Drawing must be close up of shoes and heels must be at least 3 inches high. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $200 - $250.", admin_id: 3, background_img: "heels.jpg"},
  {name: "Long Occasion Dress", category: "Dresses", end_date: "2014-12-18", description: "Design a statement piece that can be worn to special events. Drawing must be full body view and dress must be full length. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $750 - $1,000.", admin_id: 3, background_img: "longdress.jpg"},
  {name: "Sweater", category: "Sweaters", end_date: "2014-12-15", description: "Design a sweated that combines comfort with great style. Drawing must be full body view. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $100 - $150.", admin_id: 3, background_img: "sweater.jpg"},
  {name: "Trenchcoat", category: "Jackets", end_date: "2014-12-15", description: "Design a trenchcoat that is going to make its owner wish it was raining every day. Drawing must be full body view. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $150 - $200.", admin_id: 3, background_img: "trenchcoat.jpg"},  
  {name: "Men's Winter Jacket", category: "Jackets", end_date: "2014-12-18", description: "Design a jacket that is versitale for many styles. Drawing must be full body view. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $200 - $250.", admin_id: 3, background_img: "jacket.jpg"},
  {name: "Men's T-shirt", category: "T-shirts", end_date: "2014-12-25", description: "Design a unique men's t-shirt to awe any fashion lover. Drawing can be full body view or a close up of the t-shirt itself. Make sure to describe the specifics (e.g. materials) of your design. The approximate price point will be between $50 - $75.", admin_id: 3, background_img: "tshirt.jpg"},
])
Design.create!([
  {title: "Dance", designer_id: 3, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/TrUyT3EIST2bsz3xnO3I"},
  {title: "Parisian", designer_id: 13, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/a868uUTHQHLv0wA5E2So"},
  {title: "Gizmo", designer_id: 15, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/JtPzrJeTRaf5K05hwLml"},
  {title: "Rembrandt", designer_id: 17, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/TNRwf9NfRbSAAn83w51x"},
  {title: "Boulevard", designer_id: 18, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/9I49rnjXROW72K9Rd69J"},
  {title: "Lace", designer_id: 20, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/MCCOF6S5zgeblFfmvA5l"},
  {title: "Cocktail", designer_id: 24, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/3o6wX5OWTcOIRdUsUCH3"},
  {title: "Eagle", designer_id: 26, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/9XYTGdlSMymn2ZSyguwD"},
  {title: "Black Swan", designer_id: 28, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/2xbm6kunRS6bphglibWw"},
  {title: "Club", designer_id: 30, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/giOT3KnZTfWk9nM9musT"},
  {title: "Velvet", designer_id: 33, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/1FyvLU5ZTzW8r78zEUGs"},
  {title: "Sunday", designer_id: 41, challenge_id: 1, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/sXd3CcAwQYm7gRxZnrBH"},
  {title: "Rainy Day", designer_id: 3, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/XFAyF2rRTtKOba5ElHjl"},
  {title: "Sporty", designer_id: 4, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/4VbkG3mRTUyfLCD2qQma"},
  {title: "Blue Night", designer_id: 5, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/jvUSWBTmi6ZJJ5IxRzCg"},
  {title: "Urban", designer_id: 6, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/qs9leKZpSWfCVD4aDN0Q"},
  {title: "Lazy Joe", designer_id: 7, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/5X1XuGtATpqgBZccXX12"},
  {title: "Velvet", designer_id: 8, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Y7rfkW1zSu6wpoHuv0At"},
  {title: "Knit", designer_id: 9, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/VWwv9UblSOSvWMeZaHGu"},
  {title: "Harley", designer_id: 11, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/i3o0FhzzSgiI24fOeOx5"},
  {title: "Haute", designer_id: 12, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/f5c7cNVaSpGAcEAEGzoP"},
  {title: "Smokey", designer_id: 13, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/crGVSEQSP6Ak66oTDngd"},
  {title: "Archie", designer_id: 3, challenge_id: 7, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/hC3wRGXnStGHeMOu2gyZ"},
  {title: "Paris", designer_id: 20, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/2wt38AHQQ9YcYWISWqM5"},
  {title: "Strawberry", designer_id: 21, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/IP6ny8J3SPSdXIYlfDKG"},
  {title: "Classic", designer_id: 22, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/35Y58SyTv6IeoccydBmB"},
  {title: "Spring", designer_id: 23, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/PKGnLekQ6m3x3FuETaTE"},
  {title: "Breeze", designer_id: 24, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/IjDFf1ylQveBI7vwHBy8"},
  {title: "Love", designer_id: 25, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Q73P35MqRNGQ0XAQqM8O"},
  {title: "Plaid", designer_id: 26, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/q6xVq3v0TSaoXeD8VKwM"},
  {title: "Levi", designer_id: 27, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/sJbQirnpQ5S0nsoRRTjy"},
  {title: "Desert", designer_id: 28, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/eRo7pOriQBU5MARXByiA"},
  {title: "See", designer_id: 2, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/FDhH89jZShKRD9sjQthd"},
  {title: "Ambition", designer_id: 29, challenge_id: 6, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/o8CTqOw7ReKOX36hLDJY"},
  {title: "90s", designer_id: 41, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/u2LJgsRuSWuxfuCGvMr1"},
  {title: "Stripes", designer_id: 2, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Llt05skTQe6nFXPUlkHS"},
  {title: "Winter", designer_id: 2, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/IMM8ydqLTKCaDrdVPiz5"},
  {title: "Sand", designer_id: 3, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/BijarUenTSWnTNqBh4tC"},
  {title: "Funky", designer_id: 4, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/GcFOykQQXmr0L35c96mJ"},
  {title: "Paars", designer_id: 5, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/jl3p8siIR1W5kQZIm023"},
  {title: "Dark night", designer_id: 6, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/b12fhhHUTJmekiT36y7p"},
  {title: "Rainbow", designer_id: 7, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/rMjfhztNTRqyjR5fs3fA"},
  {title: "Oma", designer_id: 9, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/51ybpe37TTma5TpEN34K"},
  {title: "Urban", designer_id: 3, challenge_id: 5, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/xbQ8KgOqRnyPFqWeaf6Y"},
  {title: "Panther", designer_id: 31, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/X9oo2Qa2TTiPkHSoT9HA"},
  {title: "Secret", designer_id: 32, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/pFvybonRQq2ThxtBIz0D"},
  {title: "Brittain", designer_id: 33, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/8G7k5NRtQaqMcOQaRfOr"},
  {title: "Dragon", designer_id: 34, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/2xcpZKaAT5SPYfmOxDEZ"},
  {title: "Bloom", designer_id: 35, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/3ISwNy4WTG6bDXaCb16A"},
  {title: "Infinity", designer_id: 36, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/1R9Yin5OSeqkCaPwPSx6"},
  {title: "Barbie", designer_id: 37, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/RrKDS45Q8eA213TWURsL"},
  {title: "Garden", designer_id: 39, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/eEGRJu9oRECqUEHV9QbL"},
  {title: "Gold", designer_id: 40, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/wSHlEQJcSLmdHDmzDFtU"},
  {title: "Shark", designer_id: 41, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/LVTRLl6RSlGAJ3tmBKRs"},
  {title: "Ballet", designer_id: 42, challenge_id: 3, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/NYKzlHNaRdSHoj5lCqhy"},
  {title: "Bird", designer_id: 39, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/HlPAqeD5SwGDwFpg39ru"},
  {title: "Forest", designer_id: 38, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/U2oWQUHJQUiSAfo5Zmzq"},
  {title: "Mystic", designer_id: 37, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/uXweb7RFRmmUHtJhw7Vz"},
  {title: "Egypt", designer_id: 36, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/2OZCzay2TQipbXgomhAt"},
  {title: "Saab", designer_id: 35, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/JpiH8eIRHCmhfFqAj9xA"},
  {title: "Vogue", designer_id: 34, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/kup6WuFRR2iNfAYzaPnz"},
  {title: "Galaxy", designer_id: 2, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/rXRYdNVQ1eCkScZSdFkA"},
  {title: "Gala", designer_id: 33, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/dHzpSryzQICGx2jWpPQF"},
  {title: "Night&Day", designer_id: 32, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/l1GLDruETyaIjbVkbD5k"},
  {title: "Sexy", designer_id: 31, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/1YxLAMKhRvecs0YjzimC"},
  {title: "Godess", designer_id: 49, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Hm68kj6oQHaldrCvFsVG"},
  {title: "Satin", designer_id: 48, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Nar4ZcE5RPiU7VJgGWhh"},
  {title: "Sun", designer_id: 46, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Z8DmS3XWTmiWqfTOOKge"},
  {title: "Fantasy", designer_id: 45, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/AeD9CT9cRleMBx9PayxD"},
  {title: "Sea", designer_id: 44, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/Qo1orLOuQT6YJT38E98x"},
  {title: "Ruby", designer_id: 43, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/ii8ypw3pSgmCoBX3Q0af"},
  {title: "Leaf", designer_id: 2, challenge_id: 4, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/LfVVyUktSWO4CCeElEmH"},
  {title: "Bubbles", designer_id: 13, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/PNp2i1npSJ6Tt7fE3Z8l"},
  {title: "Sunflower", designer_id: 14, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/6qRlrSHZRCS2vNQYtzWD"},
  {title: "Lily", designer_id: 15, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/qXfRy2jJRreHw6qwYclh"},
  {title: "Abstract", designer_id: 26, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/UQOPqi1RfCvPEE98epkd"},
  {title: "Athena", designer_id: 27, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/dxY5dDWPSvGzueVbmeAJ"},
  {title: "Roxy", designer_id: 28, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/T0StljWpQteo5uigMbZw"},
  {title: "Swan", designer_id: 12, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/BamhJBPqS2ifpYYNKcFZ"},
  {title: "Flow", designer_id: 11, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/ItqriXRmGRCF2oWxa5Aw"},
  {title: "Sparkles", designer_id: 10, challenge_id: 2, description: "La marinière knitwear braid silhouette Cara D. Hermès. White shirt skort 90s razor pleats cotton. Chignon oxford chunky sole luxe Furla Givenchy statement chambray So-Cal texture. ", challenge_rank: nil, filepicker_url: "https://www.filepicker.io/api/file/lBvzT1LRSiqz10RJLgUm"},
])
Comment.create!([
  {user_id: 3, design_id: 1, body: "Love it"},
  {user_id: 2, design_id: 2, body: "Can you tell more about the design?"},
  {user_id: 2, design_id: 3, body: "Pretty!"},
  {user_id: 4, design_id: 4, body: "Love it"},
  {user_id: 5, design_id: 5, body: "Hope you will win!"},
  {user_id: 6, design_id: 6, body: "Fab"},
  {user_id: 7, design_id: 7, body: "Can't wait to wear it."},
  {user_id: 8, design_id: 8, body: "Love it"},
  {user_id: 9, design_id: 9, body: "Fab"},
  {user_id: 10, design_id: 10, body: "Which fabrics will be used?"},
  {user_id: 11, design_id: 11, body: "Can you tell more about the design?"},
  {user_id: 12, design_id: 12, body: "Wonderful"},
  {user_id: 13, design_id: 13, body: "Love it"},
  {user_id: 14, design_id: 14, body: "Pretty!"},
  {user_id: 15, design_id: 15, body: "Love it"},
  {user_id: 16, design_id: 16, body: "Amazing!"},
  {user_id: 17, design_id: 17, body: "Can you tell more about the design?"},
  {user_id: 18, design_id: 18, body: "Which fabrics will be used?"},
  {user_id: 20, design_id: 19, body: "Pretty!"},
  {user_id: 21, design_id: 20, body: "Can't wait to wear it."},
  {user_id: 22, design_id: 22, body: "So pretty"},
  {user_id: 23, design_id: 24, body: "Beautiful"},
  {user_id: 24, design_id: 24, body: "Amazing!"},
  {user_id: 25, design_id: 25, body: "Dress"},
  {user_id: 26, design_id: 26, body: "Can you tell more about the design?"},
  {user_id: 27, design_id: 27, body: "Hope you will win!"},
  {user_id: 28, design_id: 28, body: "Amazing!"},
  {user_id: 29, design_id: 29, body: "Can't wait to wear it."},
  {user_id: 30, design_id: 30, body: "Pretty!"},
  {user_id: 31, design_id: 30, body: "Hope you will win!"},
  {user_id: 32, design_id: 31, body: "Which fabrics will be used?"},
  {user_id: 33, design_id: 32, body: "Wonderful"},
  {user_id: 34, design_id: 33, body: "Can you tell more about the design?"},
  {user_id: 35, design_id: 34, body: "Need this!"},
  {user_id: 36, design_id: 35, body: "Pretty!"},
  {user_id: 37, design_id: 36, body: "To die for!"},
  {user_id: 38, design_id: 37, body: "Love it"},
  {user_id: 39, design_id: 38, body: "Awesome"},
  {user_id: 40, design_id: 39, body: "Amazing!!"},
  {user_id: 41, design_id: 41, body: "Great"},
  {user_id: 41, design_id: 41, body: "Can't wait to try it on!"},
  {user_id: 3, design_id: 42, body: "Love it"},
  {user_id: 2, design_id: 43, body: "Can you tell more about the design?"},
  {user_id: 2, design_id: 43, body: "Pretty!"},
  {user_id: 4, design_id: 44, body: "Love it"},
  {user_id: 5, design_id: 45, body: "Hope you will win!"},
  {user_id: 6, design_id: 46, body: "Fab"},
  {user_id: 7, design_id: 47, body: "Can't wait to wear it."},
  {user_id: 8, design_id: 48, body: "Love it"},
  {user_id: 9, design_id: 49, body: "Fab"},
  {user_id: 10, design_id: 50, body: "Which fabrics will be used?"},
  {user_id: 11, design_id: 50, body: "Can you tell more about the design?"},
  {user_id: 12, design_id: 51, body: "Wonderful"},
  {user_id: 13, design_id: 52, body: "Love it"},
  {user_id: 14, design_id: 53, body: "Pretty!"},
  {user_id: 15, design_id: 54, body: "Love it"},
  {user_id: 16, design_id: 55, body: "Amazing!"},
  {user_id: 17, design_id: 56, body: "Can you tell more about the design?"},
  {user_id: 18, design_id: 56, body: "Which fabrics will be used?"},
  {user_id: 20, design_id: 57, body: "Pretty!"},
  {user_id: 21, design_id: 58, body: "Can't wait to wear it."},
  {user_id: 22, design_id: 59, body: "So pretty"},
  {user_id: 23, design_id: 60, body: "Beautiful"},
  {user_id: 24, design_id: 61, body: "Amazing!"},
  {user_id: 25, design_id: 61, body: "Dress"},
  {user_id: 26, design_id: 62, body: "Can you tell more about the design?"},
  {user_id: 27, design_id: 62, body: "Hope you will win!"},
  {user_id: 28, design_id: 63, body: "Amazing!"},
  {user_id: 29, design_id: 64, body: "Can't wait to wear it."},
  {user_id: 30, design_id: 64, body: "Pretty!"},
  {user_id: 31, design_id: 65, body: "Hope you will win!"},
  {user_id: 32, design_id: 66, body: "Which fabrics will be used?"},
  {user_id: 33, design_id: 67, body: "Wonderful"},
  {user_id: 34, design_id: 68, body: "Can you tell more about the design?"},
  {user_id: 35, design_id: 69, body: "Need this!"},
  {user_id: 36, design_id: 70, body: "Pretty!"},
  {user_id: 37, design_id: 71, body: "To die for!"},
  {user_id: 38, design_id: 72, body: "Love it"},
  {user_id: 39, design_id: 73, body: "Awesome"},
  {user_id: 40, design_id: 74, body: "Amazing!!"},
  {user_id: 41, design_id: 74, body: "Great"},
  {user_id: 41, design_id: 77, body: "Can't wait to try it on!"},
])
Vote.create!([
  {design_id: 4, challenge_id: 1, user_id: 1, message: "So exciting!"},
  {design_id: 4, challenge_id: 1, user_id: 2, message: nil},
  {design_id: 2, challenge_id: 1, user_id: 3, message: nil},
  {design_id: 2, challenge_id: 1, user_id: 20, message: "I admire your work!"},
  {design_id: 3, challenge_id: 1, user_id: 21, message: nil},
  {design_id: 3, challenge_id: 1, user_id: 28, message: "Hope you will win."},
  {design_id: 3, challenge_id: 1, user_id: 29, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 23, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 24, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 25, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 26, message: "Great"},
  {design_id: 6, challenge_id: 1, user_id: 27, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 28, message: nil},
  {design_id: 6, challenge_id: 1, user_id: 32, message: nil},
  {design_id: 59, challenge_id: 4, user_id: 29, message: nil},
  {design_id: 59, challenge_id: 4, user_id: 23, message: nil},
  {design_id: 59, challenge_id: 4, user_id: 24, message: "Amazing"},
  {design_id: 59, challenge_id: 4, user_id: 31, message: nil},
  {design_id: 59, challenge_id: 4, user_id: 32, message: "Would like to see more of your work"},
  {design_id: 59, challenge_id: 4, user_id: 36, message: nil},
  {design_id: 59, challenge_id: 4, user_id: 41, message: nil},
  {design_id: 60, challenge_id: 4, user_id: 5, message: nil},
  {design_id: 61, challenge_id: 4, user_id: 6, message: "Love it"},
  {design_id: 61, challenge_id: 4, user_id: 8, message: nil},
  {design_id: 61, challenge_id: 4, user_id: 9, message: "Can't wait"},
  {design_id: 62, challenge_id: 4, user_id: 18, message: "So proud of you"},
  {design_id: 62, challenge_id: 4, user_id: 19, message: nil},
  {design_id: 62, challenge_id: 4, user_id: 34, message: nil},
  {design_id: 62, challenge_id: 4, user_id: 49, message: nil},
  {design_id: 46, challenge_id: 3, user_id: 5, message: nil},
  {design_id: 46, challenge_id: 3, user_id: 6, message: "Love it"},
  {design_id: 48, challenge_id: 3, user_id: 8, message: nil},
  {design_id: 49, challenge_id: 3, user_id: 9, message: "Can't wait"},
  {design_id: 49, challenge_id: 3, user_id: 18, message: "Love"},
  {design_id: 49, challenge_id: 3, user_id: 19, message: nil},
  {design_id: 50, challenge_id: 3, user_id: 34, message: nil},
  {design_id: 51, challenge_id: 3, user_id: 49, message: nil},
  {design_id: 74, challenge_id: 2, user_id: 41, message: "Hope you win!"},
  {design_id: 74, challenge_id: 2, user_id: 44, message: nil},
  {design_id: 74, challenge_id: 2, user_id: 46, message: nil},
  {design_id: 75, challenge_id: 2, user_id: 48, message: nil},
  {design_id: 76, challenge_id: 2, user_id: 21, message: nil},
  {design_id: 77, challenge_id: 2, user_id: 19, message: nil},
  {design_id: 77, challenge_id: 2, user_id: 18, message: nil},
  {design_id: 77, challenge_id: 2, user_id: 16, message: nil},
  {design_id: 78, challenge_id: 2, user_id: 14, message: "Just a few more days!"},
  {design_id: 78, challenge_id: 2, user_id: 12, message: nil},
  {design_id: 79, challenge_id: 2, user_id: 10, message: nil},
  {design_id: 80, challenge_id: 2, user_id: 8, message: nil},
  {design_id: 80, challenge_id: 2, user_id: 7, message: nil},
  {design_id: 82, challenge_id: 2, user_id: 5, message: nil},
  {design_id: 82, challenge_id: 2, user_id: 3, message: nil},
  {design_id: 82, challenge_id: 2, user_id: 2, message: nil},
  {design_id: 82, challenge_id: 2, user_id: 17, message: nil},                  
])
